version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/before
      timeout: 180
      runas: root
  AfterInstall:
    - location: scripts/after
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/verify.sh
      timeout: 180
      runas: root
