version: 0.0
os: linux
files:
  - source: /bob-test.zip
    destination: /tmp
hooks:
  AfterInstall:
    - location: scripts/unzip
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/verify.sh
      timeout: 180
      runas: root